-- CShang V2 Supabase schema
-- Run this in Supabase SQL Editor.
-- For production, enable RLS and create policies appropriate to your storefront/admin model.

create table if not exists public.products (
  id bigint primary key,
  slug text unique not null,
  name text not null,
  description text,
  category text not null,
  gender text not null,
  price numeric(10,2) not null,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  sku text unique not null,
  color text not null,
  size text not null,
  stock integer not null default 0,
  active boolean default true
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique not null,
  customer_name text not null,
  phone text not null,
  province text not null,
  city text not null,
  address text not null,
  note text,
  total numeric(10,2) not null,
  status text not null default 'pending_payment',
  payment_status text not null default 'unpaid',
  shipping_status text not null default 'unfulfilled',
  created_at timestamptz default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  sku text,
  product_name text not null,
  color text,
  size text,
  quantity integer not null,
  unit_price numeric(10,2) not null
);

create index if not exists product_variants_product_id_idx on public.product_variants(product_id);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

-- Example RLS baseline:
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Public storefront can read active products/variants:
create policy "public can read active products"
on public.products for select
using (active = true);

create policy "public can read active variants"
on public.product_variants for select
using (active = true);

-- IMPORTANT:
-- Do NOT create a broad public INSERT/UPDATE policy for orders in production.
-- Use a secure server-side Edge Function for order creation/payment confirmation,
-- validate prices and stock server-side, then insert the order transactionally.
